;[pytest]
;testpaths = Tests
;python_files = *test*.py
;python_functions = *test*

[pytest]
markers =
    smoke: Критически важные тесты для быстрой проверки
    cart: Тесты функциональности корзины
    positive: Позитивные тест-кейсы
    delete: Тесты удаления товаров
    e2e: Сквозные end-to-end тесты
    full_cycle: Тесты полного цикла

testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*